services:
  ollama:
    image: ollama/ollama:0.9.0
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  app:
    build:
      context: .
    image: tsgames/llm-image-tager:latest
    environment:
      MODEL: ${MODEL}
      PROMPT: ${PROMPT}
      OLLAMA_HOST: ${OLLAMA_HOST}
      DEBUG: ${DEBUG:-false}
    command: python main.py

volumes:
  ollama: