services:
  # requires a synology nas with 8+ GB memory minimum!
  ollama:
    image: ollama/ollama:0.9.0
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  app:
    image: tsgames/llm-image-tager:latest
    environment:
      MODEL:
      PROMPT:
      OLLAMA_HOST:
      IMAGE_SIZE:
    volumes:
      - ${IMAGE_PATH}:/mnt/images

volumes:
  ollama: