services:
  ollama:
    image: ollama/ollama:0.9.0
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  app:
    build:
      context: .
    image: tsgames/llm-image-tager:latest
    environment:
      MODEL:
      PROMPT:
      OLLAMA_HOST:
    volumes:
      - ${IMAGE_PATH}:/mnt/images

volumes:
  ollama: