services:
  # requires a synology nas with 8+ GB memory minimum!
  ollama:
    image: ollama/ollama:0.9.0
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  app:
    image: tsgames/llm-image-tager:latest
    environment:
      MODEL:
      PROMPT:
      OLLAMA_HOSTS:
      IMAGE_SIZE:
    volumes:
      - "img_share:/mnt/images"

volumes:
  ollama:
  img_share:
    driver: local
    # we need to use a nfs share mount. Otherwise, synology will not detect changes and trigger the indexer
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=127.0.0.1,rw
      device: ":/volume2/photo/_Test"
